### ISSUE TITLE
Install FFI

### ISSUE THREAD

**Issue by kdambekalns** [flownative/docker-php#12]
https://www.php.net/manual/en/book.ffi.php should be enabled to allow use of [jcupitt/vips](https://packagist.org/packages/jcupitt/vips) v2

**Comment by kdambekalns** [comment]
Then again…

> php-vips does not yet support preloading, so you need to enable FFI globally. This has some security implications, since anyone who can run php on your server can use it to make calls off into any native library they can find.
>
> Of course if attackers are running their own PHP code on your webserver you are probably already toast, unfortunately.

**Comment by kitsunet** [comment]
Aber:

> php-vips uses [php-ffi](https://www.php.net/manual/en/book.ffi.php) to call directly into the libvips binary. It introspects the library binary and presents the methods it finds as members of the Image class.
This means that the API you see depends on the version of libvips that php-vips finds at runtime, and not on php-vips. php-vips documentation assumes you are using the latest stable version of the libvips library.
The previous php-vips version that relied on a binary extension and not on php-ffi is still available and supported in [the 1.x branch](https://github.com/libvips/php-vips/tree/1.x).

Könnten wir irgendwie einfach auf den 1.x branch fixieren? Also z.B. könnten wir sagen, dass das Projekte tun sollen.

**Comment by kitsunet** [comment]
Neee, klar, aber wir können ja sagen, dass die Leute das so intallieren

**Comment by kdambekalns** [comment]
The documentation on https://www.flownative.com/en/documentation/guides/beach/neos-cms-vips-for-faster-image-rendering.html now explains the FFI situation.
