### ISSUE TITLE
Placeholders not replaced in container

### ISSUE THREAD

**Issue by kdambekalns** [flownative/docker-php#7]
The variable placeholders in

https://github.com/flownative/docker-php/commit/d651a2921d0ec1898713adb7666a0f5154c5cb83#diff-4be1f19baa793be4f943674742e76a30cd34ac3041d014fd954bde299b2dad8eR266-R268

are kept unchanged in the container, which seems wrong:

```ini
opcache.preload = ${PHP_OPCACHE_PRELOAD}

xdebug_enable=${PHP_XDEBUG_ENABLE}
```
*/opt/flownative/php/etc/php.ini*

**Comment by kdambekalns** [comment]
Also, `xdebug_enable` seems rather unrelated to https://github.com/flownative/docker-php/commit/d651a2921d0ec1898713adb7666a0f5154c5cb83 and is a non-existent option AFAIK.

**Comment by robertlemke** [comment]
This should be all correct and working. The placeholders are not placeholders, but are valid php.ini configuration. PHP substitutes the environment variables by their actual values during runtime (see https://www.php.net/manual/en/configuration.file.php#example-36).

The `xdebug_enable` worked at some point at least, but Xdebug support is generally unfinished.

**Comment by kdambekalns** [comment]
> PHP substitutes the environment variables by their actual values during runtime

TIL
